drop table USER if exists;

CREATE TABLE USER
(
  ID BIGINT IDENTITY PRIMARY KEY
, USERNAME VARCHAR2(50) NOT NULL
, FIRSTNAME VARCHAR2(50)
, LASTNAME VARCHAR2(50)
, VERSION INT
, CREATED_AT TIMESTAMP NOT NULL
, MODIFIED_AT TIMESTAMP NOT NULL
);